### ISSUE TITLE
Perguntas sobre o projeto

### ISSUE THREAD

**Issue by bitcoinuser** [misesdev/emptio#1]
Olá, 

Sempre quis algo assim no Nostr, algo simples que permitisse publicar notas padronizadas de compra e venda de bitcoins e que as trocas fossem baseadas simplesmente na reputação. 

Como esse projeto emptio irá funcionar? 

Obrigado.

**Comment by emptioapp** [comment]
Olá!

Bem, este projeto se propõe a resolver o problema da centralização na compra de Bitcoin. Em todos os casos em que você precisa comprar Bitcoin de forma fácil e segura, você sempre acabará em uma empresa que solicitará seus documentos e vinculará sua carteira. Existem problemas intrínsecos e evidentes nisso. Além disso, há o problema do P2P, onde aqueles que desejam vender Bitcoin sem KYC e recebem muitas transações têm suas contas bancárias bloqueadas, e assim por diante. Então, ao observar as ferramentas já existentes, percebi que é possível implementar uma solução descentralizada para esses problemas.

A maioria das tentativas de resolver esse problema, seja por falta de percepção ou por puro desejo de lucro, surge através de empresas. Ou seja, estão tentando resolver um problema descentralizado de forma centralizada, enquanto já existem ferramentas para resolver isso de maneira descentralizada. O que falta é o incentivo.

O problema do incentivo é que não há como lucrar implementando uma ferramenta que não está centralizada e que você não controla. Portanto, este é um problema de incentivo que percebi que não será solucionado sem uma prova de trabalho semelhante à de Satoshi.

Então, este projeto se propõe a resolver esses problemas e ser uma ferramenta totalmente sob o controle do usuário, utilizando o Nostr como protocolo de comunicação. Nele, você controla seus relés ou até mesmo pode executar o seu próprio relé, tendo total controle. Não há controle meu ou de qualquer organização sobre o que você faz com essa ferramenta. E o problema do incentivo deve ficar a cargo dos usuários. No futuro, se eu ou outros desenvolvedores quisermos continuar mantendo este projeto sem qualquer intenção de lucro, o projeto terá sucesso. Caso contrário, poderá existir com base em doações dos usuários. Porém, isso se refere apenas ao ponto de vista de escrever código, lançar novas funcionalidades, melhorar a ferramenta, etc., pois uma vez publicada e instalada em seu smartphone, se não houver bugs ou problemas de segurança, não dependerá de mantenedores em tempo integral.

Esta é uma ferramenta que estou fundamentalmente desenvolvendo porque é tudo o que eu gostaria que existisse. É o complemento ao Bitcoin, ao Nostr e às tecnologias descentralizadas, e que ainda não existe apenas devido ao problema do incentivo.
